services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres-leaderboard
    environment:
      - 'POSTGRES_DB=leaderboard_db'
      - 'POSTGRES_PASSWORD=Vieira0104%'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - leaderboard-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  leaderboard-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leaderboard-app
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - leaderboard-network

volumes:
  postgres_data:

networks:
  leaderboard-network:
    driver: bridge
