services:
  postgres:
    image: 'postgres:17-alpine'
    container_name: postgres-leaderboard
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - leaderboard-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  leaderboard-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leaderboard-app
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - API_SECURITY_TOKEN_SECRET=${API_SECURITY_TOKEN_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - leaderboard-network

volumes:
  postgres_data:

networks:
  leaderboard-network:
    driver: bridge
